[tool.poetry]
name = "tg-bot-test"
version = "0.1.0"
description = ""
authors = ["you"]

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
aiogram = "3.2.0"
aiosqlite = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
